-   name: mercure
    type: golang:1.18
    source:
        root: mercure
    variables:
      env:
        MERCURE_VERSION: "0.14.0"
        SERVER_NAME: :8888
        MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
        MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
    disk: 1024
    mounts:
      'db':
        source: local
        source_path: db
    hooks:
        build: |
          wget https://github.com/dunglas/mercure/releases/download/v${MERCURE_VERSION}/mercure_${MERCURE_VERSION}_Linux_x86_64.tar.gz
          gunzip mercure_${MERCURE_VERSION}_Linux_x86_64.tar.gz
          tar xvf mercure_${MERCURE_VERSION}_Linux_x86_64.tar
    web:
        commands:
            start: ./mercure run -config Caddyfile.platform_sh
        locations:
            /:
                allow: false
                passthru: true
                request_buffering:
                  enabled: false